package org.rspeer.game.api;

public enum VarpComposite {

    RUN_MODE(463),
    PRAYER_POINTS(3274),
    ABYSS_ENTERABLE(101),
    ADRENALINE(679),
    ANAGOGIC_ORTS(2006),
    AUTO_CASTING(0),
    CHARGE_PACK_COUNT(5984),
    DUNGEON_TOKENS(1097),
    ECTO_TOKENS(6533),
    FAMILIAR_SPECIAL_POINTS(1787),
    MTA_ALCHEMIST_POINTS(1347),
    MTA_ENCHANTMENT_POINTS(1348),
    MTA_GRAVEYARD_POINTS(1348),
    MTA_TELEKINETIC_POINTS(1347),
    RUN_ENABLED(463),
    RUNECRAFTING_POUCHES_FILLED(3214),
    RUNESPAN_POINTS(3220),
    SLAYER_MONSTER_CATEGORY(185),
    SLAYER_POINTS(2092),
    SLAYER_TASK_KILLS_LEFT(183),
    TOKKUL(6526),
    WARRIORS_GUILD_ATTACK_POINTS(3066),
    WARRIORS_GUILD_BALANCE_POINTS(3067),
    WARRIORS_GUILD_COMBAT_POINTS(3067),
    WARRIORS_GUILD_DEFENCE_POINTS(3066),
    WARRIORS_GUILD_STRENGTH_POINTS(3068),
    CHIMES(6528),
    ANTIFIRE(1299),
    ATTACK_POT(3561),
    AUTO_RETALIATE(462),
    CURRENT_SETTINGS_TAB(3709),
    DEFENCE_POT(3563),
    EOC_COMBAT_MODE(3711),
    EOC_INTERFACE_MODE(3814),
    FOLLOWER_SETTINGS(1790),
    GAMEPLAY_SETTINGS_CATEGORY(5839),
    GRAND_EXCHANGE_OFFER_AMOUNT(136),
    GRAND_EXCHANGE_OFFER_ITEM_ID(135),
    GRAND_EXCHANGE_OFFER_PRICE(137),
    GRAND_EXCHANGE_STATE(139),
    JUJU(4908),
    LOOT_INVENTORY(5413),
    STRENGTH_POT(3531),
    SUPER_JUJU(4908),
    PRIMARY_ACTION_BAR_NUMBER(682);

    private final int index;

    VarpComposite(int index) {
        this.index = index;
    }

    public int getIndex() {
        return index;
    }

    public int getValue() {
        return Varps.getValue(index);
    }

    public interface Value {

        int RUN_MODE_ENABLED = 1;
        int RUN_MODE_DISABLED = 0;
        int GRAND_EXCHANGE_STATE_SELLING = 1;
        int GRAND_EXCHANGE_STATE_BUYING = 0;
    }
}